version: '3.7'

services:
  postgresql:
    image: postgres:latest
    container_name: caffeine_goat_db
    environment:
      POSTGRES_DB: caffeine_goat
      POSTGRES_USER: goat
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
